# Generated by Django 6.0.6 on 2026-06-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BranchDailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('total_orders', models.IntegerField(default=0, verbose_name='订单数')),
                ('pickup_count', models.IntegerField(default=0, verbose_name='揽收量')),
                ('delivery_count', models.IntegerField(default=0, verbose_name='派送量')),
                ('exception_count', models.IntegerField(default=0, verbose_name='异常量')),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='营收')),
                ('on_time_rate', models.DecimalField(decimal_places=2, default=100.0, max_digits=5, verbose_name='准时率(%)')),
            ],
            options={
                'verbose_name': '网点统计',
                'verbose_name_plural': '网点统计管理',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='日期')),
                ('total_orders', models.IntegerField(default=0, verbose_name='总订单数')),
                ('pickup_count', models.IntegerField(default=0, verbose_name='揽收量')),
                ('delivery_count', models.IntegerField(default=0, verbose_name='签收量')),
                ('in_transit_count', models.IntegerField(default=0, verbose_name='运输中')),
                ('exception_count', models.IntegerField(default=0, verbose_name='异常量')),
                ('cancelled_count', models.IntegerField(default=0, verbose_name='取消量')),
                ('pending_pickup_count', models.IntegerField(default=0, verbose_name='待揽收')),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='营收')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '每日统计',
                'verbose_name_plural': '运营数据统计',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='操作')),
                ('target_type', models.CharField(max_length=50, verbose_name='操作对象类型')),
                ('target_id', models.CharField(blank=True, max_length=50, verbose_name='操作对象ID')),
                ('detail', models.TextField(blank=True, verbose_name='详情')),
                ('ip_address', models.CharField(blank=True, max_length=50, verbose_name='IP地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志审计',
                'ordering': ['-created_at'],
            },
        ),
    ]
