# Generated by Django 6.0.6 on 2026-06-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourierProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True, verbose_name='工号')),
                ('id_card', models.CharField(max_length=18, verbose_name='身份证号')),
                ('vehicle_type', models.CharField(choices=[('electric_bike', '电动车'), ('motorcycle', '摩托车'), ('truck', '货车'), ('on_foot', '步行')], default='electric_bike', max_length=20, verbose_name='交通工具')),
                ('service_area', models.CharField(blank=True, help_text='如：朝阳区-望京街道', max_length=200, verbose_name='服务区域')),
                ('is_available', models.BooleanField(default=True, verbose_name='是否可接单')),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3, verbose_name='评分')),
                ('total_orders', models.IntegerField(default=0, verbose_name='总订单数')),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='总收入')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='入职时间')),
            ],
            options={
                'verbose_name': '快递员信息',
                'verbose_name_plural': '快递员管理',
            },
        ),
        migrations.CreateModel(
            name='DailyWorkSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('pickups', models.IntegerField(default=0, verbose_name='揽收数')),
                ('deliveries', models.IntegerField(default=0, verbose_name='派件数')),
                ('completed', models.IntegerField(default=0, verbose_name='已完成')),
                ('exceptions', models.IntegerField(default=0, verbose_name='异常件数')),
                ('income', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='当日收入')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '工作日报',
                'verbose_name_plural': '工作日报管理',
            },
        ),
        migrations.CreateModel(
            name='DeliveryTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('pickup', '揽收'), ('deliver', '派送')], max_length=10, verbose_name='任务类型')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('assigned', '已分配'), ('accepted', '已接单'), ('in_progress', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=15, verbose_name='任务状态')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='分配时间')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='接单时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('route_order', models.IntegerField(default=0, verbose_name='路线排序')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '派送任务',
                'verbose_name_plural': '派送任务管理',
                'ordering': ['route_order', 'assigned_at'],
            },
        ),
    ]
