# Generated by Django 6.0.6 on 2026-06-26 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('couriers', '0001_initial'),
        ('orders', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courierprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='courier_profile', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='dailyworksummary',
            name='courier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_summaries', to=settings.AUTH_USER_MODEL, verbose_name='快递员'),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='courier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='快递员'),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_tasks', to='orders.order', verbose_name='订单'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyworksummary',
            unique_together={('courier', 'date')},
        ),
    ]
