# Generated by Django 6.0.6 on 2026-06-26 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(db_index=True, max_length=20, verbose_name='运单号')),
                ('status', models.CharField(choices=[('created', '已创建'), ('waiting_pickup', '待揽收'), ('picked_up', '已揽收'), ('in_transit', '运输中'), ('arrived_station', '到达驿站'), ('delivering', '派送中'), ('delivered', '已签收'), ('exception', '异常'), ('returned', '已退回')], max_length=20, verbose_name='状态码')),
                ('status_desc', models.CharField(max_length=100, verbose_name='状态描述')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='当前位置')),
                ('operator', models.CharField(blank=True, max_length=50, verbose_name='操作人')),
                ('operate_time', models.DateTimeField(verbose_name='操作时间')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_logs', to='orders.order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '物流轨迹',
                'verbose_name_plural': '物流轨迹管理',
                'ordering': ['-operate_time'],
                'indexes': [models.Index(fields=['tracking_id'], name='tracking_tr_trackin_b75479_idx'), models.Index(fields=['order'], name='tracking_tr_order_i_b6059a_idx')],
            },
        ),
    ]
