# Generated by Django 6.0.6 on 2026-06-26 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FreightTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('express_company', models.CharField(max_length=20, verbose_name='快递公司编码')),
                ('mode', models.CharField(choices=[('weight', '按重量计费'), ('volume', '按体积计费'), ('piece', '按件计费')], default='weight', max_length=10, verbose_name='计费模式')),
                ('first_weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='首重(kg)')),
                ('first_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='首重价格')),
                ('additional_weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='续重(kg)')),
                ('additional_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='续重价格')),
                ('free_shipping_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='包邮门槛(元)')),
                ('remote_area_surcharge', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='偏远地区附加费')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('version', models.CharField(blank=True, max_length=20, verbose_name='版本号')),
                ('effective_date', models.DateField(verbose_name='生效日期')),
                ('expire_date', models.DateField(blank=True, null=True, verbose_name='失效日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '运费模板',
                'verbose_name_plural': '运费模板管理',
            },
        ),
        migrations.CreateModel(
            name='InsuranceRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='最低保价金额')),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='最高保价金额')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='费率(%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '保价费率',
                'verbose_name_plural': '保价费率配置',
            },
        ),
        migrations.CreateModel(
            name='FreightRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=50, verbose_name='省份')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='城市')),
                ('district', models.CharField(blank=True, max_length=50, verbose_name='区县')),
                ('first_price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='首重价格(覆盖)')),
                ('additional_price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='续重价格(覆盖)')),
                ('surcharge', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='附加费')),
                ('is_remote_area', models.BooleanField(default=False, verbose_name='偏远地区')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='pricing.freighttemplate', verbose_name='模板')),
            ],
            options={
                'verbose_name': '运费规则',
                'verbose_name_plural': '运费规则管理',
            },
        ),
    ]
