# Generated by Django 6.0.6 on 2026-06-26 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anomalies', '0001_initial'),
        ('orders', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalyticket',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='处理人'),
        ),
        migrations.AddField(
            model_name='anomalyticket',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_tickets', to='orders.order', verbose_name='关联订单'),
        ),
        migrations.AddField(
            model_name='anomalyticket',
            name='reporter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_tickets', to=settings.AUTH_USER_MODEL, verbose_name='上报人'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='orders.order', verbose_name='关联订单'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL, verbose_name='投诉人'),
        ),
        migrations.AddIndex(
            model_name='anomalyticket',
            index=models.Index(fields=['status'], name='anomalies_a_status_33634a_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalyticket',
            index=models.Index(fields=['priority'], name='anomalies_a_priorit_59eb85_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalyticket',
            index=models.Index(fields=['anomaly_type'], name='anomalies_a_anomaly_067441_idx'),
        ),
    ]
