# Generated by Django 6.0.6 on 2026-06-26 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='网点名称')),
                ('address', models.CharField(max_length=200, verbose_name='地址')),
                ('contact_person', models.CharField(max_length=50, verbose_name='联系人')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('province', models.CharField(max_length=50, verbose_name='省份')),
                ('city', models.CharField(max_length=50, verbose_name='城市')),
                ('district', models.CharField(max_length=50, verbose_name='区县')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='纬度')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='经度')),
                ('open_time', models.TimeField(default='08:00', verbose_name='营业开始时间')),
                ('close_time', models.TimeField(default='20:00', verbose_name='营业结束时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='正常营业')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '网点',
                'verbose_name_plural': '网点管理',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='驿站名称')),
                ('address', models.CharField(max_length=200, verbose_name='地址')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='纬度')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='经度')),
                ('open_time', models.TimeField(default='08:00', verbose_name='营业开始时间')),
                ('close_time', models.TimeField(default='22:00', verbose_name='营业结束时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='正常营业')),
                ('pick_code_config', models.CharField(choices=[('phone_last6', '手机号后6位'), ('random_6', '6位随机码'), ('custom', '自定义')], default='phone_last6', max_length=20, verbose_name='取件码规则')),
                ('max_retention_days', models.IntegerField(default=3, verbose_name='最长保管天数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='stations.branch', verbose_name='所属网点')),
            ],
            options={
                'verbose_name': '驿站',
                'verbose_name_plural': '驿站管理',
            },
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelf_no', models.CharField(max_length=20, verbose_name='货架编号')),
                ('zone', models.CharField(blank=True, help_text='如A/B/C区或手机尾号分区', max_length=10, verbose_name='分区')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelves', to='stations.station', verbose_name='驿站')),
            ],
            options={
                'verbose_name': '货架',
                'verbose_name_plural': '货架管理',
                'unique_together': {('station', 'shelf_no')},
            },
        ),
        migrations.CreateModel(
            name='StationInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(max_length=20, verbose_name='运单号')),
                ('pick_code', models.CharField(max_length=20, verbose_name='取件码')),
                ('storage_time', models.DateTimeField(auto_now_add=True, verbose_name='入库时间')),
                ('out_time', models.DateTimeField(blank=True, null=True, verbose_name='出库时间')),
                ('status', models.IntegerField(choices=[(0, '在库'), (1, '已取'), (2, '滞留'), (3, '已退回')], default=0, verbose_name='库存状态')),
                ('operator', models.CharField(blank=True, max_length=50, verbose_name='操作人')),
                ('receiver_name', models.CharField(blank=True, max_length=50, verbose_name='取件人姓名')),
                ('receiver_phone', models.CharField(blank=True, max_length=20, verbose_name='取件人电话')),
                ('verification_method', models.CharField(blank=True, choices=[('pick_code', '取件码'), ('phone', '手机号'), ('id_card', '身份证')], max_length=20, verbose_name='验证方式')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='orders.order', verbose_name='订单')),
                ('shelf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stations.shelf', verbose_name='货架')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='stations.station', verbose_name='驿站')),
            ],
            options={
                'verbose_name': '驿站库存',
                'verbose_name_plural': '驿站库存管理',
                'indexes': [models.Index(fields=['tracking_id'], name='stations_st_trackin_714209_idx'), models.Index(fields=['station', 'status'], name='stations_st_station_ba7144_idx'), models.Index(fields=['pick_code'], name='stations_st_pick_co_087250_idx')],
            },
        ),
    ]
