# Generated by Django 6.0.6 on 2026-06-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_phone', models.CharField(max_length=20, verbose_name='接收手机号')),
                ('channel', models.CharField(choices=[('sms', '短信'), ('wechat', '微信服务通知'), ('voice', '语音提醒')], max_length=10, verbose_name='通知渠道')),
                ('notify_type', models.CharField(choices=[('pickup_reminder', '取件提醒'), ('delivery_notify', '派件通知'), ('异常_alert', '异常预警'), ('overdue_reminder', '滞留催取'), ('status_update', '状态更新')], max_length=20, verbose_name='通知类型')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('template_id', models.CharField(blank=True, max_length=100, verbose_name='模板ID')),
                ('is_sent', models.BooleanField(default=False, verbose_name='已发送')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='发送时间')),
                ('is_read', models.BooleanField(default=False, verbose_name='已读')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '通知记录',
                'verbose_name_plural': '通知记录管理',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('channel', models.CharField(choices=[('sms', '短信'), ('wechat', '微信服务通知'), ('voice', '语音提醒')], max_length=10, verbose_name='通知渠道')),
                ('template_id', models.CharField(max_length=100, verbose_name='厂商模板ID')),
                ('content_template', models.TextField(help_text='支持变量：{name}, {pick_code}, {station}, {address}, {time}', verbose_name='内容模板')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '通知模板',
                'verbose_name_plural': '通知模板管理',
            },
        ),
    ]
