# Generated by Django 6.0.6 on 2026-06-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_no', models.CharField(max_length=32, unique=True, verbose_name='工单编号')),
                ('source', models.CharField(choices=[('courier_report', '快递员上报'), ('user_complaint', '用户投诉'), ('system_alert', '系统预警')], max_length=20, verbose_name='来源')),
                ('anomaly_type', models.CharField(choices=[('wrong_address', '地址错误'), ('cant_reach', '联系不上'), ('package_damaged', '包裹破损'), ('rejected', '拒收退回'), ('out_of_area', '超区无法派送'), ('lost', '包裹丢失'), ('delayed', '滞留超时'), ('other', '其他')], max_length=20, verbose_name='异常类型')),
                ('description', models.TextField(verbose_name='问题描述')),
                ('images', models.TextField(blank=True, help_text='JSON数组存储图片URL', verbose_name='图片凭证')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高')], default='medium', max_length=10, verbose_name='优先级')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('resolved', '已解决'), ('closed', '已关闭')], default='pending', max_length=15, verbose_name='工单状态')),
                ('handler_remark', models.TextField(blank=True, verbose_name='处理备注')),
                ('resolution', models.TextField(blank=True, verbose_name='处理结果')),
                ('report_time', models.DateTimeField(auto_now_add=True, verbose_name='上报时间')),
                ('handle_time', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('close_time', models.DateTimeField(blank=True, null=True, verbose_name='关闭时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '异常工单',
                'verbose_name_plural': '异常工单管理',
                'ordering': ['-report_time'],
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_type', models.CharField(choices=[('delayed', '配送延迟'), ('damaged', '包裹破损'), ('lost', '快件丢失'), ('service', '服务态度'), ('wrong_delivery', '错送'), ('other', '其他')], max_length=20, verbose_name='投诉类型')),
                ('description', models.TextField(verbose_name='投诉内容')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('resolved', '已解决'), ('closed', '已关闭')], default='pending', max_length=10, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='解决时间')),
            ],
            options={
                'verbose_name': '用户投诉',
                'verbose_name_plural': '投诉管理',
                'ordering': ['-created_at'],
            },
        ),
    ]
