# Generated by Django 6.0.6 on 2026-06-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=32, unique=True, verbose_name='订单号')),
                ('tracking_id', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='运单号')),
                ('sender_name', models.CharField(max_length=50, verbose_name='寄件人姓名')),
                ('sender_phone', models.CharField(max_length=20, verbose_name='寄件人电话')),
                ('sender_province', models.CharField(max_length=50, verbose_name='寄件省份')),
                ('sender_city', models.CharField(max_length=50, verbose_name='寄件城市')),
                ('sender_district', models.CharField(max_length=50, verbose_name='寄件区县')),
                ('sender_address', models.CharField(max_length=200, verbose_name='寄件详细地址')),
                ('receiver_name', models.CharField(max_length=50, verbose_name='收件人姓名')),
                ('receiver_phone', models.CharField(max_length=20, verbose_name='收件人电话')),
                ('receiver_province', models.CharField(max_length=50, verbose_name='收件省份')),
                ('receiver_city', models.CharField(max_length=50, verbose_name='收件城市')),
                ('receiver_district', models.CharField(max_length=50, verbose_name='收件区县')),
                ('receiver_address', models.CharField(max_length=200, verbose_name='收件详细地址')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='重量(kg)')),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='体积(m³)')),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='长度(cm)')),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='宽度(cm)')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='高度(cm)')),
                ('goods_type', models.CharField(max_length=50, verbose_name='物品类别')),
                ('goods_desc', models.TextField(blank=True, verbose_name='物品描述')),
                ('is_insured', models.BooleanField(default=False, verbose_name='是否保价')),
                ('insured_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='保价金额')),
                ('freight_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='运费')),
                ('insurance_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='保价费')),
                ('packaging_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='包装费')),
                ('total_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='总费用')),
                ('pay_type', models.IntegerField(choices=[(1, '在线支付'), (2, '到付')], default=1, verbose_name='付款方式')),
                ('pay_status', models.IntegerField(choices=[(0, '未支付'), (1, '已支付'), (2, '退款中'), (3, '已退款')], default=0, verbose_name='支付状态')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('express_company', models.CharField(max_length=20, verbose_name='快递公司编码')),
                ('pick_up_time', models.DateTimeField(blank=True, null=True, verbose_name='预约取件时间')),
                ('packaging_method', models.CharField(blank=True, max_length=50, verbose_name='包装方式')),
                ('is_collect_on_delivery', models.BooleanField(default=False, verbose_name='是否代收货款')),
                ('cod_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='代收金额')),
                ('order_status', models.CharField(choices=[('waiting_pickup', '待揽收'), ('picked_up', '已揽收'), ('in_transit', '运输中'), ('delivering', '派送中'), ('delivered', '已签收'), ('exception', '异常'), ('cancelled', '已取消')], default='waiting_pickup', max_length=20, verbose_name='订单状态')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('sign_image', models.URLField(blank=True, verbose_name='签收凭证图片')),
                ('sign_photo', models.URLField(blank=True, verbose_name='包裹拍照凭证')),
                ('sign_time', models.DateTimeField(blank=True, null=True, verbose_name='签收时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单管理',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_no', models.CharField(max_length=64, unique=True, verbose_name='支付流水号')),
                ('pay_type', models.CharField(choices=[('wxpay', '微信支付'), ('alipay', '支付宝'), ('balance', '预充值')], max_length=20, verbose_name='支付方式')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='支付金额')),
                ('pay_status', models.CharField(choices=[('pending', '处理中'), ('success', '成功'), ('failed', '失败'), ('refunded', '已退款')], max_length=20, verbose_name='支付状态')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '支付记录',
                'verbose_name_plural': '支付记录管理',
            },
        ),
    ]
